eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
      host: localhost
server:
  port: 8080
spring:
  h2:
    console:
      enabled: true
#http://localhost:8080/h2-console/
  application:
    name: order-service
