eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    host: localhost
server:
  port: 8081
spring:
  h2:
    console:
      enabled: true
  application:
    name: payment-service